### ISSUE TITLE
VCR not behaving correctly on Travis

### ISSUE THREAD

**Issue by thisiscab** [glossier/solidus_retail#27]
I'm having big trouble with VCR at the moment, where the behavior is different on Travis compared to locally. 

Locally everything is green and I see that it uses the cassette correctly. When I look at the request URL of my cassettes, it requests at the proper URL which is:
`https://1b7f63bf248831c7ae2beacf9bc30bbb:b1c915515d08e2037930a844f7436610@glossier-pop-staging.myshopify.com/x/y.json`

When pushing to Travis, it makes requests to `https://glossier-pop-staging.myshopify.com/x/y`, which makes the requests fails due to VCR raising this error: `VCR::Errors::UnhandledHTTPRequestError`.

The way I setup the ShopifyURL is the following:
https://github.com/glossier/solidus_retail/blob/69e5e6c906ed64f3a631a477c805ccd5d6e1bf33/config/initializers/shopify.rb

Here is how I'm saving the cassettes: 

``` ruby
      if example.metadata[:type] == :request
        name = example.metadata[:full_description].split(/\s+/, 2).join('/').underscore.tr('.', '/').gsub(/[^\w\/]+/, '_').gsub(/\/$/, '')
        VCR.use_cassette(name, {}, &example)
      else
        VCR.turned_off(&example)
      end
```

The ENVS variables are correctly set.

DW indirectly suggested that we mock the requests based on the domain name instead of the full URL by doing the following: https://github.com/glossier/solidus_retail/blob/321aac51dc215ad1a77e15f68e72adb62c281380/spec/support/vcr.rb

The problem with this implementation is that it seems to always return the same value when the same requests is being called multiple times in-within the same block. So if I fetch the number of Posts from the API at the beginning of my spec and later on down the road I refetch the number of posts, since the requests already exists it will return me the result of the first call, which is bonker and not what I want, since this makes my whole spec suite go red.

Any suggestions? :slightly_smiling_face:

**Comment by DanielWright** [comment]
I will take a look at fixing up our VCR situation when I work on this next. :+1:

How much of a blocker is this?

**Comment by thisiscab** [comment]
All the PR that are ready to be merged related to the product/variant exporters can't be merge onto master if those specs aren't running on Travis. The features are tested and work locally though. 

I would have loved to get them on master before EOW since every extra branch that we add, adds a potential for conflicts. 

Once everything is on master, we'll be able to correct include the gem into Glossier and set it up so that we can play with it and iterate on it.

**Comment by DanielWright** [comment]
K, I'll carve out some time tomorrow to figure this out. Coolio?

**Comment by thisiscab** [comment]
Sure bud! :) Thanks a lot! I'm really curious about what the solution would be, can't wait :)
