### ISSUE TITLE
Should the extension depend on environment variables?

### ISSUE THREAD

**Issue by DanielWright** [glossier/solidus_retail#39]
My take is it should not. We can _use_ environment variables to configure the extension, but I think a degree of indirection is important.

**Comment by thisiscab** [comment]
I would agree that they should not depend on environment variables 100%. 

I would like to have a configuration setting that where you would create an initializer in your main app that would specific the settings of the retail gem. I just didn't take the time to do it 💃 

That would be a good feature to add in a PR.

**Comment by braidn** [comment]
Won't the initializer's values be set by environment variables?

**Comment by thisiscab** [comment]
Yes, but at least it will be from the point of view of the main_app instead of the gem itself. 
Right now it's invisible to the user what's happening in the gem, having an initializer in the main app would let the configuration be surfaced easily.

**Comment by DanielWright** [comment]
Maybe the initializer should be converted to a generator and `rails g solidus_retail:install`'d into the host app?
